export const GET_PRODUCTSBYNAME = 'GET_PRODUCTSBYNAME';

export const GET_PRODUCTS_BY_CATEGORY_AND_SUBCATEGORY = 'GET_PRODUCTS_BY_CATEGORY_AND_SUBCATEGORY';

export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';

export const GET_SHOPPINGLIST_BY_USER_ID = 'GET_SHOPPINGLIST_BY_USER_ID';
            