// Admin_Orders
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_BY_ID = "GET_ORDERS_BY_ID";
export const GET_ORDERS_BY_STATE = "GET_ORDERS_BY_STATE"; 
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID"; 
export const PUT_STATE_TO_ORDER = "PUT_STATE_TO_ORDER";
export const PUT_TRACKING_NUMBER = "PUT_TRACKING_NUMBER";

// Products
export const GET_PRODUCTSBYNAME = "GET_PRODUCTSBYNAME";
export const GET_PRODUCTS_BY_CATEGORY_AND_SUBCATEGORY =
  "GET_PRODUCTS_BY_CATEGORY_AND_SUBCATEGORY";

// Purchase
export const POST_PURCHASE = "POST_PURCHASE";
export const GET_USER_INFORMATION = "GET_USER_INFORMATION";
export const GET_SHOPPINGLIST_BY_USER_ID = "GET_SHOPPINGLIST_BY_USER_ID";

// Shopping List
export const DELETE_SHOPPING_LIST = "DELETE_SHOPPING_LIST";

// auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
// message
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
// user
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const DELETE_AVATAR = "DELETE_AVATAR";
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";
export const UPDATE_SHIPPING_ADDRESS = "UPDATE_SHIPPING_ADDRESS";
export const DELETE_SHIPPING_ADDRESS = "DELETE_SHIPPING_ADDRESS";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
