name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]

jobs:
  load_proyect:
    runs-on: ubuntu-18.04
    steps:
      - name: load-proyect
        uses: actions/checkout@v3
        with:
          fetch-deps: 0
      - name: install-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install-dependencies
        run: npm install --no-audit --no-fund
      - name: run test
        run: npm test
      - name: deploy to heroku
        if: ${{github.event_name == 'push'}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
          # rollbackonhealthcheckfailed: true
